# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.DateTimeField(verbose_name='date seen')),
                ('browser_name', models.CharField(blank=True, choices=[('chrome', 'Chrome'), ('safari', 'Safari'), ('firefox', 'Firefox'), ('explorer', 'Internet Explorer'), ('edge', 'Microsoft Edge'), ('opera', 'Opera'), ('other', 'Other')], max_length=20, verbose_name='browser name')),
                ('browser_name_other', models.CharField(blank=True, max_length=255, verbose_name='browser name other')),
                ('browser_verson', models.CharField(blank=True, max_length=255, verbose_name='browser version')),
                ('operating_system', models.CharField(blank=True, choices=[('macosx', 'Mac OS X'), ('windows', 'Windows'), ('ios', 'IOS (IPhone)'), ('android', 'Android')], max_length=20, verbose_name='operating system')),
                ('operating_system_other', models.CharField(blank=True, max_length=255, verbose_name='operating system other')),
                ('operating_system_version', models.CharField(blank=True, max_length=255, verbose_name='operating system version')),
                ('description', models.TextField(help_text='A concise description of what the problem is. Pure description, no narrative or conversational language.', verbose_name='bug description')),
                ('severity', models.IntegerField(choices=[(10, 'Trivial'), (20, 'Minor'), (30, 'Major'), (40, 'Critical'), (50, 'Blocker')], verbose_name='severity')),
                ('priority', models.IntegerField(choices=[(10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Immediate')], verbose_name='priority')),
                ('steps_to_reproduce', models.TextField(help_text='Step by step instructions on how to reproduce this bug. Do not assume anything, the more detailed your list of instructions, the easier it is for the developer to track down the problem!', verbose_name='steps to reproduce')),
                ('actual_behavior', models.TextField(help_text='Type what happens when you follow the instructions. This is the manifestation of the bug.', verbose_name='actual behavior')),
                ('expected_behavior', models.TextField(help_text='Type what you expected to happen when you followed the instructions. This is important, because you may have misunderstood something or missed a step, and knowing what you expected to see will help the developer recognize that.', verbose_name='expected behavior')),
                ('troubleshooting', models.TextField(blank=True, help_text='Describe anything you did to try to fix it on your own.', verbose_name='troubleshooting/testing Steps Attempted')),
                ('workaround', models.TextField(blank=True, help_text='If you found a way to make the program work in spite of the bug, describe how you did it here.', verbose_name='workaround')),
                ('status', models.IntegerField(choices=[(10, 'Open'), (20, 'Resolved'), (30, 'Closed')], default=10, verbose_name='status')),
                ('screenshot', models.ImageField(blank=True, upload_to='bugs', verbose_name='screenshot')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='submitter')),
            ],
            options={
                'verbose_name_plural': 'bugs',
                'ordering': ('-created',),
                'verbose_name': 'bug',
            },
        ),
    ]
