# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='browser_verson',
            new_name='browser_version',
        ),
        migrations.AlterField(
            model_name='bug',
            name='actual_behavior',
            field=models.TextField(help_text='Type what happens when you follow the instructions.\nThis is the manifestation of the bug.', verbose_name='actual behavior'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(help_text='A concise description of what the problem is.\nPure description, no narrative or conversational language.', verbose_name='bug description'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='expected_behavior',
            field=models.TextField(help_text='Type what you expected to happen when you followed the instructions.\nThis is important, because you may have misunderstood something or missed a step, and knowing what you expected to see will help the developer recognize that.', verbose_name='expected behavior'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='upload a helpful screenshot if you have one', upload_to='bugs', verbose_name='screenshot'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='steps_to_reproduce',
            field=models.TextField(help_text='Step by step instructions on how to reproduce this bug.\nDo not assume anything, the more detailed your list of instructions, the easier it is for the developer to track down the problem!', verbose_name='steps to reproduce'),
        ),
    ]
